databases:
  - name: skincheck-db
    plan: free

services:
  - type: web
    name: skincheck-api
    env: docker
    plan: free

    # Variables de Entorno
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skincheck-db
          property: connectionString
      
      - fromGroup: skincheck-secrets
