# Definir los servicios
services:
  - type: web
    name: skincheck-api
    env: docker
    plan: free

    # Variables de Entorno Secretas
    envVarGroups:
      - name: skincheck-secrets

# Definir las bases de datos a nivel raíz
databases:
  - name: skincheck-db
    plan: free
